### ISSUE TITLE
Not able to import into notebook

### ISSUE THREAD

**Issue by vinven7** [CambridgeMolecularEngineering/chemdataextractor2#1]
I installed cde2 using git clone. The installation went well but I am not able to import it into jupyter notebook. Getting the following error:

`ModuleNotFoundError: No module named 'tabledataextractor'`

**Comment by chemlynx** [comment]
Hi @vinven7, I encountered this issue too. The solution is to first clone the other repository in this account (tabledatatextractor) and install that before you try to install chemdataextractor (reading the installation guide for tabledataextractor, it seems you can even install in a single step: https://cambridgemolecularengineering-tabledataextractor.readthedocs-hosted.com/en/latest/installation.html). I hope that this helps

**Comment by ti250** [comment]
Sorry for the delay in replying, this is fixed now with the latest update (we actually uploaded things to PyPI), and just pip install chemdataextractor2 should work now.
