### ISSUE TITLE
The parser does not detect the comma

### ISSUE THREAD

**Issue by tcaceresm** [CambridgeMolecularEngineering/chemdataextractor2#17]
Hi!
I was creating a parser to detect specific molecules. Everything works very well, except that it does not detect commas.
For example:
2,3-dimethylamine
If I apply this parser:
`W('2') + W(',') + W('3') + W('-') + I('dimethylamine).add_action(merge)`
it doesn't work only because of the comma.
Any ideas?

**Comment by ti250** [comment]
Try printing your sentence's raw tokens with `print(sentence.raw_tokens)` and see how it's tokenised. I assume that here the comma is included so that it's tokenised as `["2,3", "-", "dimethylamine"]` or something along those lines.

**Comment by tcaceresm** [comment]
> it's tokenised as ["2,3", "-", "dimethylamine"]

yes, you are right! Thanks for your quick response. I rewrote the parser and so far it works fine.
