### ISSUE TITLE
Error on trying to pip install ChemdataExtractor

### ISSUE THREAD

**Issue by chemlynx** [CambridgeMolecularEngineering/chemdataextractor2#4]
Following on from @ti250 's comment on issue 1 I tried to do a fresh install of ChemDataExtractor2.

I created a fresh conda environment with python 3.9.7, activated it and then ran: pip install chemdataextractor2

This resulted in the the following error message:

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
chemdataextractor2 depends on TableDataExtractor@ git+https://github.com/CambridgeMolecularEngineering/tabledataextractor

**Comment by ti250** [comment]
Thank you for trying this out, I wasn't aware of this restriction. I'll try to fix this soon. 
In the meantime, `pip install git+https://github.com/CambridgeMolecularEngineering/chemdataextractor2` should hopefully work.

**Comment by ti250** [comment]
Sorry for the delay - this should be fixed now
