### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Kox1nga** [CambridgeMolecularEngineering/chemdataextractor2#40]
Windows 11
Python 3.10.9
Cannot pip install chemdataextractor2
The error is:“_PyGen_Send”: undefined symbol when using spacy<2.2,>=2.1.0
Already installed vs cpp toolkit.
Looking forward for your response, thx!

**Comment by OBrink** [comment]
The recent version of ChemDataExtractor has issues with conflicting dependencies and many systems, and looking at the number of open issues that report similar problems, I don't think that CDE is currently actively maintained. At some point, I have given up trying to install it the normal way, but you can easily use it with Docker. All you need to do is to install Docker and run the image according to the documentation [here](https://hub.docker.com/repository/docker/obrink/chemdataextractor/general).

**Comment by Kox1nga** [comment]
Please accept my sincere appreciation for your reply.
And I will try to use Docker at your suggestion.
Best wishes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CambridgeMolecularEngineering/chemdataextractor2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CambridgeMolecularEngineering/chemdataextractor2] Cannot install (Issue #40)





 
The recent version of ChemDataExtractor has issues with conflicting dependencies and many systems, and looking at the number of open issues that report similar problems, I don't think that CDE is currently actively maintained. At some point, I have given up trying to install it the normal way, but you can easily use it with Docker. All you need to do is to install Docker and run the image according to the documentation here.
