### ISSUE TITLE
Implementation of an Abstract Class

### ISSUE THREAD

**Issue by ViktorWeissenborn** [CambridgeMolecularEngineering/chemdataextractor2#46]
Hello (:

In ChemDataExtractor there are different document classes like the Title class, Heading class, Paragraph class and so on.

For me it would be very handy to also have an "Abstract" class that gives me the abstract of an article as easy as a Heading class gives me the heading and the Title class gives me the title of an article. Currently the Abstract of an article will be included in a Paragraph object and is therefore hard to identify as the abstract. It is often unclear if the extracted text of the paragraph objects under doc.elements is part of the abstract or part of a normal paragraph from another part of the document. Though for elsevier XML documents for example an abstract is clearly defined with its corresponding XML tags inside the XML document.

Would there be an "easy" or "quick" way to implement an Abstract class into ChemDataExtractor?

If so, let me know, I would be happy to take care of it myself, but I am not really sure where to start and how many dependent classes, functions and variables need to be changed...

kind regards
Viktor

**Comment by Dingyun-Huang** [comment]
For Elsevier, yes! Elsevier XMLs have a distinct xml decorator for abstracts/graphical abstracts. The files you'd want to change are `reader.elsevier` and `scrape.pub.elsevier`.
