### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: The specified account is disabled.

### ISSUE THREAD

**Issue by 51Yy** [CambridgeMolecularEngineering/chemdataextractor2#47]
Hello, 

Thanks for sharing your great work in data mining!

Here is my issue:
I have installed chemdataextractor2 by using 'pip install chemdataextractor2'. During the installation, it worked well, but when I tried to import the chemdataextractor2, it raised an error like this:

![error](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/assets/94936207/7b2658f0-2f7f-4aa1-b99f-dfe6138f7dcb)

It seemed like it failed to access the 'scibert_cased_vocab_1.0.txt' because of the account permissions. I didn't know if it was my mistaken installation or something else

Could you tell me how to solve this? for example, providing a link to download these files (I noticed that four files are required) for use?

Thanks!

**Comment by Dingyun-Huang** [comment]
Hi there,

Can you run `cde data where` and the output will be the directory where the models and data are stored. Please post a screen shot of the content because I'd like to check if it's only for this particular file or not.

Best,
Dingyun

**Comment by 51Yy** [comment]
Hi Dingyun,


Thanks for your kind help!


I would like to get the data files via email, and here is my email: ***@***.***


Best wishes,
Yiyang Wu
























At 2023-12-15 00:13:56, "DINGYUN HUANG" ***@***.***> wrote:

Hi there,

The online sharing repository has expired, and we are getting it renewed as soon as possible. If you are in a hurry, I can share the files through email and please place these in the output of cde data where command.

Something like this
image.png (view on web)

Do the import and it should work out.

Best wishes,
Dingyun

**Comment by Dingyun-Huang** [comment]
Hi there, 

I cannot see the email address. Do you mind commenting on GitHub web page instead of replying to the email notification please? Or you can drop me a message at dh582@cam.ac.uk.

Best wishes,
Dingyun

**Comment by 51Yy** [comment]
Hi dingyun, 

I'm sorry for my carelessness. Here is my email address: yiyangwu2021@163.com.

Thanks for your kind help

Best wishes,
yiyang

**Comment by minhiiii** [comment]
@Dingyun-Huang 

Hi dingyun,

I am also experiencing the same issue as yiyang, and I would like to know if it's possible to send me the model files.

My email is fkfajsl@korea.ac.kr. 

I appreciate your kind help.

Best Regards,
Minhi Han

**Comment by Lacyam** [comment]
Hi dingyun,

I am also experiencing the same issue as yiyang, and I would like to know if it's possible to send me the model files. 
I hope it will be available soon. Thanks.

My email is xyyang0516@163.com

Thank you very much.

Best wishes,
Xiaoyan Yang

**Comment by AhmetTasdemir** [comment]
I am encountering an issue during the Docker build process where the models required by ChemDataExtractor are not being downloaded successfully. pip install --no-cache-dir chemdataextractor2 worked fine but the build log indicates the following:

![image](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/assets/79527973/34bd2bba-d749-4785-82e5-e9510a181d6d)


Environment:

ChemDataExtractor version: 2
Python version: 3.8
Docker version: 24.0.7
Steps to Reproduce:

Run the Docker build with the provided Dockerfile.
Observe the failure in downloading the required models.

Expected Behavior:
I expected the Docker build process to successfully download the required models for ChemDataExtractor.

Actual Behavior:
The models are not being downloaded, and the build process is failing with the mentioned error.

My e-mail is ahmettsdmr1312@gmail.com

Thank you for your time

Best Regards,
Ahmet Taşdemir.

**Comment by OscartGiles** [comment]
Do you have a timeframe for when the data hosting will be resolved?

**Comment by hsurana299** [comment]
Hi dingyun,

I am also experiencing the same issue as yiyang, and I would like to know if it's possible to send me the model files.
I hope it will be available soon. Thanks.

My email is [hsurana299@gmail.com]

Thank you very much.

Best wishes,
Harsh Surana

**Comment by Dingyun-Huang** [comment]
Hi there, the issue has been addressed. Hopefully it can get updated to PyPi and Conda in a few days.

**Comment by OscartGiles** [comment]
> Hi there, the issue has been addressed. Hopefully it can get updated to PyPi and Conda in a few days.

Excellent thanks. Is the data being hosted at the same address, or have you found another provider?

**Comment by Dingyun-Huang** [comment]
> > Hi there, the issue has been addressed. Hopefully it can get updated to PyPi and Conda in a few days.
> 
> Excellent thanks. Is the data being hosted at the same address, or have you found another provider?

It is in a new Azure account, the link in the package to these files have been edited to reference the new source. The installing procedure will stay the same.

**Comment by Dingyun-Huang** [comment]
This should now be fixed.
