### ISSUE TITLE
Unable to Download Models During Docker Build

### ISSUE THREAD

**Issue by AhmetTasdemir** [CambridgeMolecularEngineering/chemdataextractor2#48]
I am encountering an issue during the Docker build process where the models required by ChemDataExtractor are not being downloaded successfully. pip install --no-cache-dir chemdataextractor2 worked fine but the build log indicates the following:

![image](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/assets/79527973/34bd2bba-d749-4785-82e5-e9510a181d6d)

Environment:

ChemDataExtractor version: 2
Python version: 3.8
Docker version: 24.0.7
Steps to Reproduce:

Run the Docker build with the provided Dockerfile.
Observe the failure in downloading the required models.

Expected Behavior:
I expected the Docker build process to successfully download the required models for ChemDataExtractor.

Actual Behavior:
The models are not being downloaded, and the build process is failing with the mentioned error.

Thank you for your time

Best Regards,
Ahmet Taşdemir.

**Comment by ti250** [comment]
This should now be fixed thanks to @Dingyun-Huang

**Comment by Dingyun-Huang** [comment]
Hi there, I am closing this issue as the links to models and files have been updated.
