### ISSUE TITLE
Dependency 'pdfminer.six' now need to be specified to lower than 20221105 for python verion <= 3.7

### ISSUE THREAD

**Issue by Cubakki** [CambridgeMolecularEngineering/chemdataextractor2#51]
The package pdfminer.six's new version '20231228' has removed the support for python 3.6 and 3.7. 
When installing chemdataextractor2  without using requirement.txt, an error will occur because file 'setup.py'  does not specify the version of pdfminer.six if python version <= 3.7 .

**Comment by Dingyun-Huang** [comment]
This has been fixed in the repo. Still awaiting to be released to PyPI.
