### ISSUE TITLE
about  installing

### ISSUE THREAD

**Issue by VVLFFF** [CambridgeMolecularEngineering/chemdataextractor2#54]
Hi ! I have downloaded python3.8 and Microsoft visual C++ build Tools, but when I enter "pip install chemdataextractor2" , the anaconda prompt will report errors. And even though I downloaded this project, when I enter "python setup.py install", it still showed errors. Could you please tell me where the problem is?

**Comment by Dingyun-Huang** [comment]
Please post the entire output of your installation command.

**Comment by jghasemi44** [comment]
Try to download visual studio c++ Builder and این the tab of development.... Check mark the builder according your windows version...

**Comment by Dingyun-Huang** [comment]
Closing as there is no follow-up information. Reopen if needed.
