### ISSUE TITLE
Deploying ChemDataExtractor v2 on Cloud Platforms

### ISSUE THREAD

**Issue by zhome1226** [CambridgeMolecularEngineering/chemdataextractor2#57]
I successfully installed ChemDataExtractor v2 using the Docker image you shared. However, while it managed to process one research paper without issues, I encountered a kernel crash error when attempting to extract from another. I suspect this might be due to insufficient memory. Is there a way to deploy ChemDataExtractor v2 onto cloud servers like Google Colab or Kaggle to overcome this memory limitation?

**Comment by Dingyun-Huang** [comment]
Please post your code and console output. ChemDataExtractor should work fine with and without GPU and on a regular personal laptop.

**Comment by zhome1226** [comment]
I'm in the process of setting up a virtual environment on macOS, and I attempted to install ChemDataExtractor using pip. However, I encountered the following error during the installation process: " note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output." 

when I use "conda install -c conda-forge chemdataextractor -y",it shows "UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==14.1=0
  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__osx==14.1=0
  - feature:|@/osx-arm64::__unix==0=0
  - chemdataextractor -> click -> __unix
  - chemdataextractor -> click -> __win
  - chemdataextractor -> lxml -> __osx[version='>=10.9|>=11.0']

Your installed version is: 14.1
"
Is it due to the MacOs system or my improper operation？

**Comment by Dingyun-Huang** [comment]
First, you should use pip to install chemdataextractor2, as we haven't released the newest version of CDE2 to conda.

I need more info to debug your installation:

* Make sure your Python version is 3.8.
* Please post the entire output trace of the `pip install chemdataextractor2`.
* What is your output if you run `which gcc` in terminal?

**Comment by zhome1226** [comment]
1.my Python version of virtual environment is 3.8.19 
2.there is the whole code when I input pip install chemdataextractor2:
Requirement already satisfied: chemdataextractor2 in ./anaconda3/envs/cde/lib/python3.8/site-packages/chemdataextractor2-2.3.2-py3.8.egg (2.3.2)
Requirement already satisfied: wheel>=0.37.0 in ./anaconda3/envs/cde/lib/python3.8/site-packages (from chemdataextractor2) (0.43.0)
Collecting appdirs (from chemdataextractor2)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting beautifulsoup4 (from chemdataextractor2)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting boto3==1.15.18 (from chemdataextractor2)
  Using cached boto3-1.15.18-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting botocore==1.18.18 (from chemdataextractor2)
  Using cached botocore-1.18.18-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting click==6.7 (from chemdataextractor2)
  Using cached click-6.7-py2.py3-none-any.whl.metadata (424 bytes)
Collecting cssselect (from chemdataextractor2)
  Using cached cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting lxml (from chemdataextractor2)
  Using cached lxml-5.2.2.tar.gz (3.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting nltk (from chemdataextractor2)
  Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting python-dateutil (from chemdataextractor2)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting requests==2.21.0 (from chemdataextractor2)
  Using cached requests-2.21.0-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting six (from chemdataextractor2)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting python-crfsuite (from chemdataextractor2)
  Using cached python-crfsuite-0.9.10.tar.gz (478 kB)
  Preparing metadata (setup.py) ... done
Collecting tabledataextractor (from chemdataextractor2)
  Using cached tabledataextractor-1.5.10.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting PyYAML (from chemdataextractor2)
  Using cached PyYAML-6.0.1.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting selenium==3.141.0 (from chemdataextractor2)
  Using cached selenium-3.141.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting protobuf==3.* (from chemdataextractor2)
  Using cached protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Collecting yaspin (from chemdataextractor2)
  Using cached yaspin-2.5.0-py3-none-any.whl.metadata (14 kB)
Collecting deprecation (from chemdataextractor2)
  Using cached deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting allennlp==0.9.0 (from chemdataextractor2)
  Using cached allennlp-0.9.0-py3-none-any.whl.metadata (11 kB)
Collecting tokenizers==0.12.1 (from chemdataextractor2)
  Using cached tokenizers-0.12.1.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scikit-learn==0.22.1 (from chemdataextractor2)
  Using cached scikit-learn-0.22.1.tar.gz (6.9 MB)
  Preparing metadata (setup.py) ... done
Collecting overrides==3.1.0 (from chemdataextractor2)
  Using cached overrides-3.1.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting stanza==1.6.1 (from chemdataextractor2)
  Using cached stanza-1.6.1-py3-none-any.whl.metadata (13 kB)
Collecting DAWG-Patched (from chemdataextractor2)
  Using cached DAWG-Patched-0.9.1.tar.gz (376 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy<1.23,>=1.16 in ./anaconda3/envs/cde/lib/python3.8/site-packages/numpy-1.22.4-py3.8-macosx-11.1-arm64.egg (from chemdataextractor2) (1.22.4)
Requirement already satisfied: pdfminer.six in ./anaconda3/envs/cde/lib/python3.8/site-packages/pdfminer.six-20231228-py3.8.egg (from chemdataextractor2) (20231228)
Collecting torch>=1.2.0 (from allennlp==0.9.0->chemdataextractor2)
  Using cached torch-2.3.0-cp38-none-macosx_11_0_arm64.whl.metadata (26 kB)
Collecting spacy<2.2,>=2.1.0 (from allennlp==0.9.0->chemdataextractor2)
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [153 lines of output]
      Collecting setuptools
        Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
      Collecting wheel<0.33.0,>0.32.0
        Using cached wheel-0.32.3-py2.py3-none-any.whl.metadata (2.1 kB)
      Collecting Cython
        Using cached Cython-3.0.10-py2.py3-none-any.whl.metadata (3.2 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.8-cp38-cp38-macosx_11_0_arm64.whl.metadata (8.4 kB)
      Collecting preshed<2.1.0,>=2.0.1
        Using cached preshed-2.0.1.tar.gz (113 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.10-cp38-cp38-macosx_11_0_arm64.whl.metadata (2.0 kB)
      Collecting thinc<7.1.0,>=7.0.8
        Using cached thinc-7.0.8.tar.gz (1.9 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blis<0.3.0,>=0.2.1 (from thinc<7.1.0,>=7.0.8)
        Using cached blis-0.2.4.tar.gz (1.5 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting wasabi<1.1.0,>=0.0.9 (from thinc<7.1.0,>=7.0.8)
        Using cached wasabi-0.10.1-py3-none-any.whl.metadata (28 kB)
      Collecting srsly<1.1.0,>=0.0.6 (from thinc<7.1.0,>=7.0.8)
        Using cached srsly-1.0.7-cp38-cp38-macosx_11_0_arm64.whl.metadata (13 kB)
      Collecting numpy>=1.7.0 (from thinc<7.1.0,>=7.0.8)
        Using cached numpy-1.24.4-cp38-cp38-macosx_11_0_arm64.whl.metadata (5.6 kB)
      Collecting plac<1.0.0,>=0.9.6 (from thinc<7.1.0,>=7.0.8)
        Using cached plac-0.9.6-py2.py3-none-any.whl.metadata (1.5 kB)
      Collecting tqdm<5.0.0,>=4.10.0 (from thinc<7.1.0,>=7.0.8)
        Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
      Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
      Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)
      Using cached Cython-3.0.10-py2.py3-none-any.whl (1.2 MB)
      Using cached cymem-2.0.8-cp38-cp38-macosx_11_0_arm64.whl (41 kB)
      Using cached murmurhash-1.0.10-cp38-cp38-macosx_11_0_arm64.whl (26 kB)
      Using cached numpy-1.24.4-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
      Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
      Using cached srsly-1.0.7-cp38-cp38-macosx_11_0_arm64.whl (366 kB)
      Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
      Using cached wasabi-0.10.1-py3-none-any.whl (26 kB)
      Building wheels for collected packages: preshed, thinc, blis
        Building wheel for preshed (setup.py): started
        Building wheel for preshed (setup.py): finished with status 'done'
        Created wheel for preshed: filename=preshed-2.0.1-cp38-cp38-macosx_11_1_arm64.whl size=71309 sha256=0420f59e5d3128383cf548448b07f2aaf0e1b1cb9fa911d30e2071737b2bda22
        Stored in directory: /Users/zhome/Library/Caches/pip/wheels/5a/d0/29/7f6993a759349eae3d0ecca7e2fbc88acdd8650b25e6c6ad8a
        Building wheel for thinc (setup.py): started
        Building wheel for thinc (setup.py): finished with status 'done'
        Created wheel for thinc: filename=thinc-7.0.8-cp38-cp38-macosx_11_0_arm64.whl size=1952234 sha256=369bd129ad36f614ce141562860af341099ee836ed070c11aa9866f1c57bcc51
        Stored in directory: /Users/zhome/Library/Caches/pip/wheels/f4/5b/cc/8a96be826c5d22ca28e3c30f785b22edc57ffb2d349fa780be
        Building wheel for blis (setup.py): started
        Building wheel for blis (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [87 lines of output]
            BLIS_COMPILER? None
            /Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
            !!
      
                    ********************************************************************************
                    Requirements should be satisfied by a PEP 517 installer.
                    If you are using pip, you can try `pip install --use-pep517`.
                    ********************************************************************************
      
            !!
              dist.fetch_build_eggs(dist.setup_requires)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.macosx-11.1-arm64-cpython-38
            creating build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/benchmark.py -> build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/__init__.py -> build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/about.py -> build/lib.macosx-11.1-arm64-cpython-38/blis
            creating build/lib.macosx-11.1-arm64-cpython-38/blis/tests
            copying blis/tests/__init__.py -> build/lib.macosx-11.1-arm64-cpython-38/blis/tests
            copying blis/tests/test_dotv.py -> build/lib.macosx-11.1-arm64-cpython-38/blis/tests
            copying blis/tests/test_gemm.py -> build/lib.macosx-11.1-arm64-cpython-38/blis/tests
            copying blis/tests/common.py -> build/lib.macosx-11.1-arm64-cpython-38/blis/tests
            copying blis/cy.pyx -> build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/py.pyx -> build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/__init__.pxd -> build/lib.macosx-11.1-arm64-cpython-38/blis
            copying blis/cy.pxd -> build/lib.macosx-11.1-arm64-cpython-38/blis
            running build_ext
            unix
            py_compiler gcc
            {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'HOSTTYPE': 'x86_64', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/matt/repos/flame-blis', 'VIRTUAL_ENV': '/home/matt/repos/cython-blis/env3.6', 'USER': 'matt', 'PWD': '/home/matt/repos/cython-blis', 'HOME': '/home/matt', 'NAME': 'LAPTOP-OMKOB3VM', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SHLVL': '1', 'LOGNAME': 'matt', 'PATH': '/home/matt/repos/cython-blis/env3.6/bin:/tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/LLVM/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Users/matt/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matt/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/matt/AppData/Roaming/npm:/snap/bin:/mnt/c/Program Files/Oracle/VirtualBox', 'PS1': '(env3.6) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'VAGRANT_HOME': '/home/matt/.vagrant.d/', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/home/matt/repos/cython-blis/env3.6/bin/python'}
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/bulldozer/bli_cntx_init_bulldozer.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_bulldozer.o -O2 -funroll-all-loops -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/generic/bli_cntx_init_generic.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_generic.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/haswell/bli_cntx_init_haswell.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_haswell.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/penryn/bli_cntx_init_penryn.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_penryn.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/piledriver/bli_cntx_init_piledriver.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_piledriver.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/sandybridge/bli_cntx_init_sandybridge.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_sandybridge.o -O3 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/config/steamroller/bli_cntx_init_steamroller.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_cntx_init_steamroller.o -O2 -fomit-frame-pointer -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang -c /private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c -o /var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_amaxv_zen_int.o -O3 -mavx2 -mfma -mfpmath=sse -march=core-avx2 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/darwin-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64
            clang: error: unsupported argument 'core-avx2' to option '-march='
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/setup.py", line 235, in <module>
                setup(
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
                return distutils.core.setup(**attrs)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
                return run_commands(dist)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
                dist.run_commands()
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
                self.run_command("build")
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                self.distribution.run_command(command)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                self.run_command(cmd_name)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                self.distribution.run_command(command)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
                self.build_extensions()
              File "/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/setup.py", line 105, in build_extensions
                objects = self.compile_objects(compiler.split('-')[0], arch, OBJ_DIR)
              File "/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/setup.py", line 184, in compile_objects
                objects.append(self.build_object(env=env, **spec))
              File "/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/setup.py", line 198, in build_object
                subprocess.check_call(command, cwd=BLIS_DIR)
              File "/Users/zhome/anaconda3/envs/cde/lib/python3.8/subprocess.py", line 364, in check_call
                raise CalledProcessError(retcode, cmd)
            subprocess.CalledProcessError: Command '['clang', '-c', '/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c', '-o', '/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/tmp2qncq_qb/bli_amaxv_zen_int.o', '-O3', '-mavx2', '-mfma', '-mfpmath=sse', '-march=core-avx2', '-fPIC', '-std=c99', '-D_POSIX_C_SOURCE=200112L', '-DBLIS_VERSION_STRING="0.5.0-6"', '-DBLIS_IS_BUILDING_LIBRARY', '-Iinclude/darwin-x86_64', '-I./frame/3/', '-I./frame/ind/ukernels/', '-I./frame/1m/', '-I./frame/1f/', '-I./frame/1/', '-I./frame/include', '-I/private/var/folders/09/0yl4fd352yq594klt1b0sc9m0000gn/T/pip-install-zuol8x8t/blis_6acf4e7eb62c47779a3d84f8db4e1f6c/blis/_src/include/darwin-x86_64']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for blis
        Running setup.py clean for blis
      Successfully built preshed thinc
      Failed to build blis
      ERROR: Could not build wheels for blis, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
3.when I run which gcc, here is what I saw in terminal
/usr/bin/gcc

Is it due to  my improper operation？

**Comment by Dingyun-Huang** [comment]
I am not sure if you closed this by accident. But just to double check if you have successfully installed ChemDataExtractor? check [here](https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1) for possible solution. It's likely a compiler issue with Apple M-series CPU. Update your clang to 13.0.0 solved the problem in the above link.
