### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by OPPOSITEFOOLS** [CambridgeMolecularEngineering/chemdataextractor2#60]
Hello, I am using windows and python 3.8. The C++ dev tools were installed, although I didn't install them, particularly for this. I think it should be working. 

When I use pip install chemdataextractor2, it tries collecting spacy and shows an error when installing build dependencies. And then lots of red lines and yellow lines appear, I think it tries to use another version of spacy?
![image](https://github.com/CambridgeMolecularEngineering/chemdataextractor2/assets/26300990/2427107f-ec00-4e2d-9845-e8068e701378)

But finally it just stuck and I have to cancel it manually. 
[output.txt](https://github.com/user-attachments/files/16088280/output.txt)
And this is the output.

It will be so good if someone could help me out with this. Thank you!

**Comment by Dingyun-Huang** [comment]
Have you tried create a new and fresh virtual environment (e.g. conda) and install chemdataextractor2?

**Comment by OPPOSITEFOOLS** [comment]
> Have you tried create a new and fresh virtual environment (e.g. conda) and install chemdataextractor2?

I have tried creating new clean python environment, and it also ends up with this problem. I am not used to using conda, will that make big differences?

**Comment by OPPOSITEFOOLS** [comment]
ERROR: Could not build wheels for blis, which is required to install pyproject.toml-based projects

I also tried conda just now, and yeah it is still struggling building wheels. :(

**Comment by Dingyun-Huang** [comment]
Hi,  could you post the output when you tried installing in a conda environment?

**Comment by OPPOSITEFOOLS** [comment]
[output.txt](https://github.com/user-attachments/files/16111157/output.txt)
[output2.txt](https://github.com/user-attachments/files/16111176/output2.txt)
These are the outputs with conda.

**Comment by Dingyun-Huang** [comment]
The following link might be relevant to you, as suggested line 89 and 90 in your output2.txt file.

>clang -c C:\Users\gaoti\AppData\Local\Temp\pip-install-c3prijv3\blis_ddabaedcf446421ea869e7d90de8c585\blis\_src\config\bulldozer\bli_cntx_init_bulldozer.c -o C:\Users\gaoti\AppData\Local\Temp\tmpgf353u9g\bli_cntx_init_bulldozer.o -O2 -funroll-all-loops -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude\windows-x86_64 -I.\frame\3\ -I.\frame\ind\ukernels\ -I.\frame\1m\ -I.\frame\1f\ -I.\frame\1\ -I.\frame\include -IC:\Users\gaoti\AppData\Local\Temp\pip-install-c3prijv3\blis_ddabaedcf446421ea869e7d90de8c585\blis\_src\include\windows-x86_64
error: [WinError 2] The system cannot find the file specified

https://stackoverflow.com/questions/61669873/python-venv-env-fails-winerror-2-the-system-cannot-find-the-file-specified

**Comment by OPPOSITEFOOLS** [comment]
I don't think that works for me. I have tried run it as admin it still returns the same thing. 
[output.txt](https://github.com/user-attachments/files/16118443/output.txt)
This is the entire process what I did. does it usually work for others if they do the same? I am thinking about reinstalling.

**Comment by OPPOSITEFOOLS** [comment]
I also tried it in a new google colab notebook, it returns the same error.

**Comment by Dingyun-Huang** [comment]
Hi there,
I just managed to reproduce the error, I will take a look into it. Meanwhile, you can try using Windows SubSystem, where you can have an Linux environment on windows. The installation is much easier on Linux (also better tested with GitHub Action).

**Comment by Dingyun-Huang** [comment]
Hi, I think the short answer for this is  **use Python 3.7**. Though SpaCy 2.1.9 will work on Python 3.8, it would require manual compilation from source on Windows platform.

**Comment by OPPOSITEFOOLS** [comment]
Yes python 3.7 works for me. And by the way, I'm working with ChemDataExtractor and using it to parse documents for specific information, such as catalyst mass. I've implemented a parser based on the provided examples, and it works well for extracting entries that match my regular expressions. However, I have a question about handling documents with multiple entries that mention catalyst mass. In some cases, there are multiple mentions of catalyst mass, but only one of them is relevant to my extraction needs.

How can I improve my parsing to ensure that only the relevant entry is extracted? Is it primarily about refining the regular expressions further, or are there additional strategies or tools within ChemDataExtractor that can help distinguish between relevant and non-relevant entries? Any guidance or best practices for this kind of selective extraction would be greatly appreciated.

**Comment by Dingyun-Huang** [comment]
Hi there, there is no direct way to determine which property/catalyst entries are "relevant". Can you open a new issue and post your detailed example there such that we can figure out what you need.
