### ISSUE TITLE
Issues Installing chemdataextractor2 on Windows - Build Errors with blis and preshed

### ISSUE THREAD

**Issue by HeJLDLUT** [CambridgeMolecularEngineering/chemdataextractor2#64]
Hello, I am encountering some difficulties while trying to install chemdataextractor2 on my Windows machine. Specifically, I am facing errors during the build process for the blis and preshed packages, which are preventing the installation from completing successfully. Below are some details of the errors I am seeing:

"
Building wheels for collected packages: blis, preshed
  Building wheel for blis (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      ...
      error: [WinError 2] The system cannot find the file specified.
  ERROR: Failed building wheel for blis

  Building wheel for preshed (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      ...
      TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
  ERROR: Failed building wheel for preshed
"

These errors occurred after running 'pip install chemdataextractor2' in a newly created Python 3.8 environment.

I have tried the following steps to resolve the issue, but unfortunately, the problem persists:

Using pip install --use-pep517 as suggested in the error message.
Ensuring that my Python environment and related tools (such as Visual Studio Build Tools) are up to date.
Attempting the installation within an Anaconda environment.
Here are some details about my setup:

Operating System: Windows 10
Python Version: 3.8
Package Manager: Anaconda

**Comment by Dingyun-Huang** [comment]
Please try using Python 3.7 to resolve this build error.

**Comment by HeJLDLUT** [comment]
> 请尝试使用 Python 3.7 解决此构建错误。
Thank you. Problem solved！
